version: '3.8'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123qweA@
    networks:
          - restapi_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - restapi_network

  # Zookeeper - kafka service discovery
  # Will open port 2181 to host port
  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - restapi_network

  # Kafka server
  # Start with standalone mode
  # Non-authenticated and topic auto creating
  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    networks:
      - restapi_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - restapi_network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=es1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - restapi_network

#  es-head:
#    image: marlic/elasticsearch-head
#    environment:
#      http.cors.enabled: true
#      http.cors.allow-origin: "*"
#    ports:
#      - "9100:80"
#    networks:
#      - restapi_network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123qweA@

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.8.1
#    container_name: kifarunix-demo-kibana
#    environment:
#      ELASTICSEARCH_URL: http://kifarunix-demo-es:9200
#      ELASTICSEARCH_HOSTS: http://kifarunix-demo-es:9200
#    ports:
#      - 5601:5601
#    networks:
#      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: ls1
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    networks:
      - restapi_network

networks:
  restapi_network:
