package _const

const PARAM_PRODUCT_ID = "PRODUCT_ID"
const PARAM_PRODUCT_NAME = "PRODUCT_NAME"
const PARAM_MIN_PRICE = "MIN_PRICE"
const PARAM_MAX_PRICE = "MAX_PRICE"
const PARAM_BRANCH_ID = "BRANCH_ID"

const DATA_TYPE_NUMBER = "NUMBER"
const DATA_TYPE_STRING = "STRING"

const EVENT_TYPE_SEARCHING = "SEARCHING"
const EVENT_TYPE_FILTERING = "FILTERING"
const EVENT_TYPE_VIEWING = "VIEWING"
